Adding context Contact Preference element to Join Form
nycmeshnet/meshforms pull request #65
Opened 2024-08-07 00:32 UTC by had2020

2024-08-07 00:33 UTC, had2020 commented
this adds the element needed for the Add "Contact Preference field to member object" issue

2024-08-09 02:01 UTC, WillNilges requested changes
:wave: Thanks for the PR. Is this supposed to be a draft? If so, cool, but if not, there's more that needs doing here.

- I see that you have a PR open in `meshdb` (https://github.com/nycmeshnet/meshdb/pull/452). Please get those changes merged first, so that the field has somewhere to go.
    - While you're at it, update the Join Form endpoint to accept this new data, but make sure that it's optional (so that the join form will still work until this PR gets merged)
- Update the Meshforms API model to send the new data
- Write some unit tests to make sure that the Join Form is working properly. We have playwright setup in this repo, so you could use that and create some kind of mock endpoint.

2024-08-09 02:01 UTC, WillNilges commented on components/JoinForm/JoinForm.tsx
> +          <input type="text" name="ContactPreference" placeholder="Contact Preference" required />
This should be a set of radio buttons with two options:
- `Email`
- `Phone`

Email should be the default.

2024-08-09 03:19 UTC, WillNilges commented
Also can you link the ticket from our backlog/launch tracker? 
https://github.com/orgs/nycmeshnet/projects/4/views/1

2024-08-13 17:51 UTC, closed without merging